apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atc.fullname" . }}-config
  labels:
    {{- include "atc.labels" . | nindent 4 }}
data:
  atc-config.yaml: |
{{ .Values.config.strategiesYaml | indent 4 }}
