name: Validate Backend
on:
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/pr-backend.yml'
permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Build Frontend
        run: make build-frontend
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --timeout=5m
          install-only: true
      - name: Lint Backend
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make lint-backend
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Build Frontend
        run: make build-frontend
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: v1.13.0
      - run: make test
      - name: Install Consul
        run: |
          wget https://releases.hashicorp.com/consul/2.0.2/consul_2.0.2_linux_amd64.zip
          unzip consul_2.0.2_linux_amd64.zip
          sudo mv consul /usr/local/bin/
          rm consul_2.0.2_linux_amd64.zip
      - name: Run Integration Tests
        run: make test-integration
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Build Frontend
        run: make build-frontend
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --snapshot --clean
