name: Validate PR
on:
  pull_request:
permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Lint Frontend
        run: |
          cd frontend
          npm install
          npm run lint
      - name: Build Frontend
        run: make build-frontend
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
      - name: Lint Helm Chart
        run: helm lint deploy/helm/atc
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Build Frontend
        run: make build-frontend
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: v1.13.0
      - run: make test
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Build Frontend
        run: make build-frontend
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --snapshot --clean
